/**
 * DietTrackerApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AcitvityEnum = 0 | 1 | 2 | 3 | 4;

export const AcitvityEnum = {
    NUMBER_0: 0 as AcitvityEnum,
    NUMBER_1: 1 as AcitvityEnum,
    NUMBER_2: 2 as AcitvityEnum,
    NUMBER_3: 3 as AcitvityEnum,
    NUMBER_4: 4 as AcitvityEnum
};