/**
 * DietTrackerApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CalorieIntakeDto { 
    id?: string;
    calorieGoal?: number;
    calorieCurrent?: number;
    fatGoal?: number;
    fatCurrent?: number;
    proteinGoal?: number;
    proteinCurrent?: number;
    carbohydratesGoal?: number;
    carbohydratesCurrent?: number;
    date?: Date;
}