/**
 * DietTrackerApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ingredient } from './ingredient';
import { ObjectId } from './objectId';

export interface Recipe { 
    id?: ObjectId;
    name?: string;
    prepareTime?: number;
    difficulty?: number;
    preparation?: string;
    foodIds?: Array<Ingredient>;
    category?: string;
}