/**
 * DietTrackerApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';

export interface User { 
    picture?: ObjectId;
    id?: ObjectId;
    name?: string;
    dateOfBirth?: Date;
    gender?: string;
    goalWeight?: number;
    height?: number;
    email?: string;
    phoneNumber?: string;
    weight?: number;
    recipeIds?: Array<ObjectId>;
    activityIds?: Array<ObjectId>;
    dailyProgressIds?: Array<ObjectId>;
    calorieIntakeIds?: Array<ObjectId>;
    waterIntakeIds?: Array<ObjectId>;
    sleepIds?: Array<ObjectId>;
    achievementsIds?: Array<ObjectId>;
    activityLevel?: number;
}