export * from './achievements.service';
import { AchievementsService } from './achievements.service';
export * from './activity.service';
import { ActivityService } from './activity.service';
export * from './calorieIntake.service';
import { CalorieIntakeService } from './calorieIntake.service';
export * from './dailyProgress.service';
import { DailyProgressService } from './dailyProgress.service';
export * from './food.service';
import { FoodService } from './food.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './nutritionFact.service';
import { NutritionFactService } from './nutritionFact.service';
export * from './recipe.service';
import { RecipeService } from './recipe.service';
export * from './sleep.service';
import { SleepService } from './sleep.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './waterIntake.service';
import { WaterIntakeService } from './waterIntake.service';
export const APIS = [AchievementsService, ActivityService, CalorieIntakeService, DailyProgressService, FoodService, LoginService, NutritionFactService, RecipeService, SleepService, UserService, WaterIntakeService];
